- app/assets/stylesheets/reveal-parisrb.scss
- app/views/lineup/show.html.slim
Ajout de la date (en haut a droite) et du logo 'RubyParis' (en haut à gauche) dans le header de tous les slides.
> Add logo and date to reveal slides

- app/views/talks/_form.html.slim
Ça manque peut-être aussi dans le lineup ?
> Ajout du CoC pour les speakers

- app/controllers/talks_controller.rb
- app/models/talk.rb
- app/views/rails_admin/main/lineup.html.slim
- app/views/talk_mailer/new_talk.text.erb
- app/views/talks/_form.html.slim
- app/views/talks/index.html.slim
- config/initializers/rails_admin.rb
- config/locales/fr.yml
- db/migrate/20170812131957_add_speaker_twitter_to_talk.rb
- db/migrate/20170812140829_add_preferred_talk_month_to_talk.rb
- db/migrate/20170812155652_add_time_to_talk.rb
- db/schema.rb
@tibastral @abelards Je ne suis pas tout à fait certain de ce que vous vouliez concernant l'heure du talk, donc j'ai fait une datetime
> Add talks elements

- app/views/layouts/application.html.slim
Ajoute une balise de vérification pour les Google Web Tools.
Ajouter la variable d'environnement `GOOGLE_WEB_TOOLS_ID` pour rendre l'ajout fonctionnel.
> Implement Google Web Tools meta tag

- app/views/welcome/index.html.slim
- config/locales/fr.yml
In order to remove the mustdown gem we need to remove the use of its helpers here the mustdown helper
> Remove mustdown helper

- Gemfile
- Gemfile.lock
- app/models/talk.rb
Add slack notification to #orga when a talk is added:
> Send slack notification on new talk

- app/views/shared/_navbar.html.slim
> Remove broken links in header

- app/models/talk.rb
- db/seeds.rb
- scalingo.json
fix https://github.com/parisrb/paris-rb.org/issues/163
> feat: add seed

- test/fixtures/talks.yml
In #187 I forgot to clean the tasks seeds, so for consistency here it is
> Minor: clean talks seed after #187.

- app/models/talk.rb
Duration, leval and preferred month, plus a bit of formating.
Closes parisrb/paris-rb.org#172
> Extra info in the Slack notification for talks

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- config/tailwind.config.js
- package.json
- yarn.lock
Setup DaisiUI https://daisyui.com
> Add DaisyUI

- app/assets/stylesheets/components/typography.css
- app/helpers/application_helper.rb
- app/views/welcome/index.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- config/tailwind.config.js
> Homepage hero

- config/tailwind.config.js
- package.json
- postcss.config.js
- yarn.lock
| before | After|
|----|----|
|![CleanShot 2024-04-24 at 20 53 58@2x](https://github.com/parisrb/paris-rb.org/assets/7847244/1b006171-4247-4ac8-bcac-7a328d7b4cbe)|![CleanShot 2024-04-24 at 20 53 31@2x](https://github.com/parisrb/paris-rb.org/assets/7847244/3245261b-3d18-4f88-ad63-9d8d31a69f39)|
> add responsive font sizes

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/concerns/analytics.rb
- app/models/ahoy/event.rb
- app/models/ahoy/visit.rb
- config/initializers/ahoy.rb
- db/migrate/20240403065507_create_ahoy_visits_and_events.rb
- db/schema.rb
- test/system/home_page_test.rb
Add very basics analytics fully RGPD compliant with Ahoy
> add ahoy RGPD analytics

- app/views/application/_navbar.html.erb
- app/views/application/navbar/_link.html.erb
> add a nice view transition active nav link

- app/controllers/talks_controller.rb
- app/jobs/application_job.rb
- app/jobs/slack_notification_job.rb
- app/mailers/talk_mailer.rb
- app/models/talk.rb
- test/controllers/talks_controller_test.rb
- test/fixtures/talks.yml
extract slack notification to a dedicated job
adds the ability to test by posting to orga-dev channel from preview branches
> Slack notifier

- app/controllers/application_controller.rb
- app/controllers/welcome_controller.rb
- app/views/welcome/_data.html.erb
- app/views/welcome/index.html.erb
- config/initializers/memory_cache.rb
- config/locales/en.yml
- config/locales/fr.old.yml
- config/locales/fr.yml
- config/locales/views/welcome.en.yml
- config/locales/views/welcome.fr.yml
> Add a few Data on the community

- app/avo/resources/video.rb
- app/models/video.rb
- test/fixtures/videos.yml
With youtube we don't need anymore the thumbnail url field as we can compute it easily
> Update vimeo_thumbnail field to compute dynamically youtube urls

- app/controllers/videos_controller.rb
- app/controllers/welcome_controller.rb
- app/models/video.rb
Order correctly the videos on the home page
> order videos on welcome page in chronologically order

- app/views/videos/_card.html.erb
> Change date format on video card

- app/avo/resources/user.rb
(Permet aussi d'ajouter un utilisateur sans avoir à passer par le console)
> ✨ Utilisateur peut changer de mot de passe
