app/assets/javascripts/jobs.js.coffee
On the homepage, it would be better to have the most recent jobs.
My PR display only the jobs updated during the last 300 days.
=> Limit the number of job display on the homepage

app/models/talk.rb
J'ai voulu ajouter un talk pour le mois prochain et il me propose toujours le mois d'octobre alors que le premier mardi du mois est passé.
La PR fait en sort de cacher le mois en cours si le premier mardi du mois est passé.
=> Do not propose current month if first tuesday is in the past

Gemfile.lock
Upgrade mimemagic to get bundle install working again (because mimemagic 0.3.3 has been yanked)
=> Fix: Upgrade mimemagic

Dockerfile
In the Dockerfile there is a command to force node version to 8.x
But with latest container, there is also node 10 in the sources and `apt install -y nodejs` takes v 10.x as it is newer
Also the manual download + install was not working as it is putting node in /opt which isn't in PATH and isn't overwriting the version installed by apt which is in /usr/bin/nodejs
Before:
```
ylecuyer@inwin:~/Projects/rubyparis.org$ docker-compose build
....
ylecuyer@inwin:~/Projects/rubyparis.org$ docker-compose run web node --version
WARNING: The CLOUDINARY_URL variable is not set. Defaulting to a blank string.
WARNING: The MAIL_URL variable is not set. Defaulting to a blank string.
Creating rubyparisorg_web_run ... done
v10.24.0
```
With fix:
```
ylecuyer@inwin:~/Projects/rubyparis.org$ docker-compose …
```
=> Fix Dockerfile to really use node 8

package.json, yarn.lock
https://github.com/parisrb/rubyparis.org/pull/114 Needs to be merged first
elm 0.18 is referencing an url which isn't working anymore, we need to bump it to 0.19 there is no changelog but from wics there is no breaking changes on what we use
elm-webpack-loader also needs to be bumped to be compatible with elm 0.18
=> Fix yarn install

app/views/talks/index.html.slim, app/views/videos/show.html.slim, config/locales/fr.yml
In order to remove the mustdown gem we need to remove the use of its helpers here the markdown helper
=> Remove markdown helper

config/locales/rails_admin.fr.yml
Before:
After:
Fix comes from: https://github.com/railsadminteam/rails_admin/issues/982#issuecomment-199369370
=> Fix datetime format in date pickers

app/views/lineup/show.html.slim
=> Remove 00:00 from datetime in lineup

app/views/lineup/_social_media.slim, app/views/shared/_navbar.html.slim
Heroku app doesn't work anymore, free plan doesn't exist anymore. Using Slack link instead.
=> feat: update Slack link

app/views/talks/index.html.slim
Remove old contact email from talk page.
When a new email address is created, it will probably have to be added in place of the one that was deleted.
=> feat: remove email contact from talks page

config/initializers/cloudinary.rb
This PR adds the Cloudinary cloud_name mostly to ease the developer experience.
If we have a seed of the database with real content, having the cloud_name allows to run the project without any env variable.
The cloud_name is not a secret part of the Cloudinary credential as we can find it in all the public asset links.
```
https://res.cloudinary.com/hcdr9ti7y/image/upload/c_fill,g_center,h_100,w_180/v1669753550/ixoxmmhpxfsvshnmmlyr.jpg
```
=> add cloudinary cloud_name to the configuration

app/views/lineup/_social_media.slim, app/views/shared/_navbar.html.slim, app/views/talks/_form.html.slim, app/views/welcome/index.html.slim
as per the talk in Slack it updates the link to the meetup.
At the same time I have added target: "_blank" to most links going outside and remove the link to the CoC that is no more available on Meet Up
=> update meetup link

.gitignore, Gemfile, Gemfile.lock, Procfile.dev, app/assets/config/manifest.js, app/assets/stylesheets/application.tailwind.css, app/controllers/application_controller.rb, app/views/layouts/application.html+new.erb, bin/dev, config/tailwind.config.js
This PR install Tailwind using the tailwind-rails gem. 
To start the project you now need to either use the Profile.dev with foreman or overwind (bin/dev will start foreman automatically) or in two different terminals `rails s` and  `rails tailwindcss:watch` 
In theory Tailwind is not added yet to the main layout. To facilitate the transition a new application layout using a (+new) variant is available. To enable this new layout you can add `?new=true` to the url to display a fully broken site 😄.
This should facilitate the migration page by page to the new design
=> Add Tailwind and basic new layout for the redesign

app/models/talk.rb, app/views/lineup/_talks.slim, db/migrate/20230322213633_remove_emoji_prefix_from_talks.rb, db/schema.rb
We were adding emojis based on talk duration manually to have a nice lineup, now those emojis are automatically added.
Talk list:
How it is shown in lineup:
=> Better: Automatically add emoji based on talk duration on lineup

app/views/lineup/show.html.slim
Current slide order is strange and hard to present:
I changed it for a more natural order:
@julienmarseille I'll let you review as you'll be the one presenting them on the next meetup
=> Better: order for lineup slides.

app/models/talk.rb, config/initializers/rails_admin.rb, config/locales/fr.yml, db/migrate/20231118111323_add_priority_to_talks.rb, db/schema.rb
Since we're starting to add low-priority talks (i.e. talks that are mostly proposed to fill in a short line-up, if need be), having a clear way to point them out could be useful. And while we're at it, why not an the option of marking a talk as "high priority" so that room could be made for it (e.g. for an special guest)?
Note that this attribute is not user-facing – only admins should have the ability to decide that a talk as is low- or high-priority. By default, the priority of a talk is "normal", and this level should be kept most of time.
=> Talk priorities

db/migrate/20131124225118_create_talks.rb, db/migrate/20131201175242_create_videos.rb, db/migrate/20131201202915_create_sponsors.rb, db/migrate/20140106172253_devise_create_users.rb, db/migrate/20140106172254_create_rails_admin_histories_table.rb, db/migrate/20140107180320_create_tweets.rb, db/migrate/20140220114849_add_happened_at_to_talks.rb, db/migrate/20140221114249_add_slides_and_video_to_talks.rb, db/migrate/20140224181029_rename_video_slug_to_video_url_in_talks.rb, db/migrate/20140702174558_add_lineup_to_talks.rb, db/migrate/20141104103459_remove_lineup_from_talks.rb, db/migrate/20170812131957_add_speaker_twitter_to_talk.rb, db/migrate/20170812140829_add_preferred_talk_month_to_talk.rb, db/migrate/20170812155652_add_time_to_talk.rb, db/schema.rb
Error :
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Active Record release the migration was written for: class CreateTalks < ActiveRecord::Migration[7.0]
=> 🐛 Fix migration

config/environments/development.rb, config/storage.yml, scalingo.json
Ensure that Review App, Development and production all have their own dedicated folder in Cloudinary to avoid collisions
=> set the Cloudinary base folder by environment 

Gemfile, Gemfile.lock, config/puma.rb
switch to the config that is now provided by Rails-8 (currently main branch)
=> loosen puma version and update config as in Rails 8

test/fixtures/videos.yml
Ajouts des 3 dernières vidéos du mois de mars afin de mettre en avant les dernières vidéos et de montrer de l'activité sur le site
=> Add videos mars 2024

app/avo/resources/video.rb
=> 🚸 Indicates to the administrator that the slug field is optional

app/controllers/concerns/captcha.rb, app/controllers/talks_controller.rb, app/helpers/captcha_helper.rb, app/views/talks/_form.html.erb, test/controllers/talks_controller_test.rb
We are getting quite a few spam talks proposal
This PR adds a simple visually hidden field to the talks#form to identify bots and ignore them when this field is filed (honeypot strategy)
=> add honeypot to talk form to prevent bot spams

app/helpers/application_helper.rb, app/views/application/_footer.html.erb, app/views/lineups/_social_media.html.erb, app/views/talks/new.html.erb, app/views/welcome/index.html.erb, config/initializers/social_links.rb, config/routes.rb, test/controllers/redirection_controller_test.rb
Les liens d'invitations Slack ne durent plus que 30J : https://parisrb.slack.com/archives/C08PRJANL/p1749642499848269
- https://github.com/parisrb/paris-rb.org/issues/292
L'idée est d'avoir un lien toujours valide qui redirige (status 308) vers le bon lien afin de pouvoir avoir un lien qui reste toujours valide
=> ✨ Ajoute un lien de redirection vers le lien Slack

Gemfile.lock, config/database.yml, db/seeds.rb
The `super(key.to_sym)` error occurs because `url: paris_rb_development` is missing a URL scheme.
=> Fix non-URLs in database.yml

Gemfile, Gemfile.lock, app/jobs/application_job.rb, config/application.rb, config/environments/test.rb
SuckerPunch can ([and should](https://github.com/brandonhilkert/sucker_punch?tab=readme-ov-file#faq)) now be replaced by the built in Async adapter.
To fix the error we had the test now uses the `:test` queue adapter
Edit : Rails 7.2 live version here https://rubyparis-pr302.osc-fr1.scalingo.io/
=> remove sucker punch
